// `.env.json` is generated by the `npm run build` command
// import env from './.env.json';

export const environment = {
  production: true,
  version: '1.0.0',
  serverUrl: '',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'pl-PL'
  ]
};
